# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-03-29 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20240329_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='linkedin_job_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
