# Generated by Django 5.0.3 on 2024-03-29 22:28

import enumfields.fields
import jobs.enums
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20240329_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=enumfields.fields.EnumField(default='1', enum=jobs.enums.JobStatus, max_length=30),
        ),
    ]
