# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-03-29 18:15
from __future__ import unicode_literals

from django.db import migrations, models
import enumfields.fields
import jobs.enums


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='applies',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=enumfields.fields.EnumField(default='New', enum=jobs.enums.JobStatus, max_length=30),
        ),
    ]
