# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-03-29 20:19
from __future__ import unicode_literals

from django.db import migrations
import enumfields.fields
import jobs.enums


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20240329_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='work_type',
            field=enumfields.fields.EnumField(blank=True, enum=jobs.enums.WorkType, max_length=30, null=True),
        ),
    ]
