# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-03-29 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
